# fly.toml app configuration file generated for sung-suho-md on 2025-06-15T22:23:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sung-suho-md'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
